### ISSUE TITLE
Installation instructions via npm

### ISSUE THREAD

**Issue by oshalygin** [stormpath/stormpath.js#129]
Current instructions indicate:
````bash
npm install stormpath.js
````

should be:
````bash
npm install stormpath
````

**Comment by robertjd** [comment]
Hi @oshalygin , the `stormpath` package is a different module, it is our Node SDK, which is meant for backend applications.  But you're right, the readme is wrong, it should actually be:

```
npm install stormpath-js
```

I'll update now..
